# Generated by Django 5.0.3 on 2024-03-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_episodios', models.IntegerField()),
                ('studio', models.CharField(max_length=100)),
            ],
        ),
    ]
